env:
  browser: true
  es6: true
extends:
  - eslint:recommended
  - plugin:@typescript-eslint/recommended
  - plugin:react/recommended
  - prettier
parser: "@typescript-eslint/parser"
parserOptions:
  ecmaFeatures:
    jsx: true
  ecmaVersion: 2018
  sourceType: module
plugins:
  - react
  - "@typescript-eslint"
settings:
  react:
    version: detect
rules:
  {
    no-use-before-define: "off",
    "@typescript-eslint/explicit-module-boundary-types": "off",
    react/prop-types: "off",
  }
